const DEFAULT_COLS = 24
const COL_OPTIONS = [12, 16, 24] as const
const DEFAULT_ROW_HEIGHT = 50
const DEFAULT_GAP = 16
const DRAG_HANDLE_CLASS = 'ogrid-drag-handle'
const IDLE_TIMEOUT = 200
const MAX_TIMEOUT = 2000
const FALLBACK_H = 4
const RESPONSIVE_BREAKPOINT = 768
const MAX_GUARD_FRAMES = 10
export {
  COL_OPTIONS,
  DEFAULT_COLS,
  DEFAULT_GAP,
  DEFAULT_ROW_HEIGHT,
  DRAG_HANDLE_CLASS,
  FALLBACK_H,
  IDLE_TIMEOUT,
  MAX_GUARD_FRAMES,
  MAX_TIMEOUT,
  RESPONSIVE_BREAKPOINT
}
