const DEFAULT_COLS = 24,
  COL_OPTIONS = [12, 16, 24] as const,
  DEFAULT_ROW_HEIGHT = 50,
  DEFAULT_GAP = 16,
  DRAG_HANDLE_CLASS = 'ogrid-drag-handle',
  IDLE_TIMEOUT = 200,
  MAX_TIMEOUT = 2000,
  FALLBACK_H = 4,
  RESPONSIVE_BREAKPOINT = 768,
  MAX_GUARD_FRAMES = 10
export {
  COL_OPTIONS,
  DEFAULT_COLS,
  DEFAULT_GAP,
  DEFAULT_ROW_HEIGHT,
  DRAG_HANDLE_CLASS,
  FALLBACK_H,
  IDLE_TIMEOUT,
  MAX_GUARD_FRAMES,
  MAX_TIMEOUT,
  RESPONSIVE_BREAKPOINT
}
